
name: livequiz_realtimeservice_cluster

services:

    livequiz-realtimeservice-backend-1:
        build:
            context: .
            dockerfile: Dockerfile
        image: livequiz_realtimeservice_backend
        container_name: livequiz-realtimeservice-backend-1
        ports: 
            - "3001:3000"
        environment:
            - SERVER_HOST=0.0.0.0
            - SERVER_PORT=3000
            #- DEBUG=ioredis:*
            - HOST_TOKEN_SECRET=1e8d02c3599ea2c991e17d1be06c1fb20ce43a0b4dea4a370ee3ce19a36ea9951e04670656c68229a8572d42def6ea13a9680d52fa19946047f18963e603f52c
        networks:
            - livequiz-realtimeservice-net
            - livequiz-messagebrokers-net

networks:
    livequiz-realtimeservice-net:
        external: true
    livequiz-messagebrokers-net:
        external: true